### ISSUE TITLE
我这边ie11 打不开

### ISSUE THREAD

**Issue by zhangZYBX** [zqy233/vite-vue2-ie-template#1]
你好，请问下我这运行后chrome是能启动的，但是ie打不开，显示空白页面，
是否是跟我本地运行的node有关系  我这node 版本是 14.18.0  npm 8.15.1  请问能正常运行的版本号是多少

**Comment by zqy233** [comment]
> 你好，请问下我这运行后chrome是能启动的，但是ie打不开，显示空白页面， 是否是跟我本地运行的node有关系 我这node 版本是 14.18.0 npm 8.15.1 请问能正常运行的版本号是多少

ie是打包环境才有效，可以试下打包后的文件用vscode的live-server插件在ie打开试试

**Comment by zhangZYBX** [comment]
> > 你好，请问下我这运行后chrome是能启动的，但是ie打不开，显示空白页面， 是否是跟我本地运行的node有关系 我这node 版本是 14.18.0 npm 8.15.1 请问能正常运行的版本号是多少
> 
> vite-plugin-legacy： Production only The legacy bundle is only generated when vite build runs, because Vite never bundles during development (that's the whole point of Vite).
> 
> vite-plugin-legacy官方说明了，ie是打包环境才有效，可以试下打包后的文件用vscode的live-server插件在ie打开试试

可以了，谢谢
