### ISSUE TITLE
有没有vue3的模板呢

### ISSUE THREAD

**Issue by admin8756** [zqy233/vite-vue2-ie-template#3]
有没有vue3的模板呢

**Comment by zqy233** [comment]
你好，vue3 不支持 ie11，所以这个模板是vue2+常见vue2库，不考虑ie11，使用vue3的话我推荐antfu大佬的模板https://github.com/antfu/vitesse

**Comment by admin8756** [comment]
> 你好，vue3 不支持 ie11，所以这个模板是vue2+常见vue2库，不考虑ie11，使用vue3的话我推荐antfu大佬的模板https://github.com/antfu/vitesse

我知道vitesee的。但是我感觉你的vite配置更好一点。

**Comment by zqy233** [comment]
> > 你好，vue3 不支持 ie11，所以这个模板是vue2+常见vue2库，不考虑ie11，使用vue3的话我推荐antfu大佬的模板https://github.com/antfu/vitesse
> 
> 我知道vitesee的。但是我感觉你的vite配置更好一点。

好的，最近太忙了，后续有时间配个vue3+element-plus版本的

**Comment by admin8756** [comment]
> > > 你好，vue3 不支持 ie11，所以这个模板是vue2+常见vue2库，不考虑ie11，使用vue3的话我推荐antfu大佬的模板https://github.com/antfu/vitesse
> > 
> > 
> > 我知道vitesee的。但是我感觉你的vite配置更好一点。
> 
> 好的，最近太忙了，后续有时间配个vue3+element-plus版本的
有没有兴趣看看tdesign，其实我感觉vue2用element无可厚非，但是vue3.选择性太多了。element做的不是很好的。或者你有没有博客。可以专门写一下你是如何配置vite的。我感觉一定很多人感兴趣。

**Comment by zqy233** [comment]
@admin8756 好的，那就有时间写个文章配置[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)，unplugin-vue-components也支持tdesign的resolver

**Comment by admin8756** [comment]
非常感谢~
________________________________
发件人: zqy233 ***@***.***>
发送时间: 2023年5月16日 13:55
收件人: zqy233/vite-vue2-ie-template ***@***.***>
抄送: LeeLaa ***@***.***>; Mention ***@***.***>
主题: Re: [zqy233/vite-vue2-ie-template] 有没有vue3的模板呢 (Issue #3)


@admin8756<https://github.com/admin8756> 好的，那就有时间写个文章配置unplugin-vue-components<https://github.com/antfu/unplugin-vue-components>，unplugin-vue-components也支持tdesign的resolver

―

**Comment by zqy233** [comment]
@admin8756 不好意思，最近有点忙，unplugin-vue-components官方文档写的很好，我就做了官方文档的翻译工作，并且加上了AntDesignVueResolver的配置项，写在我的csdn上了：https://blog.csdn.net/qq_42611074/article/details/123036252?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22123036252%22%2C%22source%22%3A%22qq_42611074%22%7D

**Comment by admin8756** [comment]
> @admin8756 不好意思，最近有点忙，unplugin-vue-components官方文档写的很好，我就做了官方文档的翻译工作，并且加上了AntDesignVueResolver的配置项，写在我的csdn上了：https://blog.csdn.net/qq_42611074/article/details/123036252?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22123036252%22%2C%22source%22%3A%22qq_42611074%22%7D

感谢。我研究一下试试呢。
